// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/webhooks/:workflowId",
				Handler: TriggerWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/workflows",
				Handler: ListWorkflowsHandler(serverCtx),
			},
		},
	)
}
