// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Stage 5: split into public + JWT-protected route groups.

package handler

import (
	"net/http"

	"api-gateway/internal/middleware"
	"api-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// Public routes — no authentication required.
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/health",
			Handler: HealthHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/auth/login",
			Handler: LoginHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/webhooks/:workflowId",
			Handler: TriggerWorkflowHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/executions/:id/stream",
			Handler: ExecutionStreamHandler(serverCtx),
		},
	})

	// Protected routes — valid JWT required.
	// JWTMiddleware validates the Bearer token against Keycloak's JWKS and
	// injects userID + roles into the request context.
	jwtMW := middleware.NewJWTMiddleware(serverCtx.Config.Auth.JWKSUrl)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{jwtMW.Handle},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/workflows",
				Handler: ListWorkflowsHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/workflows",
				Handler: CreateWorkflowHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/workflows/:id",
				Handler: GetWorkflowHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPut,
				Path:    "/workflows/:id",
				Handler: UpdateWorkflowHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodDelete,
				Path:    "/workflows/:id",
				Handler: DeleteWorkflowHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/workflows/:workflowId/executions",
				Handler: ListExecutionsHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/executions/:id",
				Handler: GetExecutionHandler(serverCtx),
			},
		),
	)
}
