// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Stage 5: LoginReq / LoginResp added manually (not via goctl to avoid skeleton conflicts).

package types

type CreateWorkflowReq struct {
	Name          string `json:"name"`
	TriggerType   string `json:"triggerType"`
	TriggerConfig string `json:"triggerConfig,optional"`
	Steps         string `json:"steps,optional"`
}

type CreateWorkflowResp struct {
	Id int64 `json:"id"`
}

type DeleteWorkflowReq struct {
	Id int64 `path:"id"`
}

type DeleteWorkflowResp struct {
	Ok bool `json:"ok"`
}

type ExecutionItem struct {
	Id        int64         `json:"id"`
	Status    string        `json:"status"`
	StartedAt string        `json:"startedAt"`
	StepLogs  []StepLogItem `json:"stepLogs"`
}

type GetExecutionReq struct {
	Id int64 `path:"id"`
}

type GetWorkflowReq struct {
	Id int64 `path:"id"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type ListExecutionsReq struct {
	WorkflowId int64 `path:"workflowId"`
}

type ListExecutionsResp struct {
	Items []ExecutionItem `json:"items"`
	Total int64           `json:"total"`
}

type ListWorkflowsResp struct {
	Items []WorkflowItem `json:"items"`
	Total int64          `json:"total"`
}

type StepLogItem struct {
	Id         int64  `json:"id"`
	StepID     string `json:"stepId"`
	StepType   string `json:"stepType"`
	Status     string `json:"status"`
	Input      string `json:"input"`
	Output     string `json:"output"`
	Error      string `json:"error"`
	DurationMs int64  `json:"durationMs"`
}

type StreamExecutionReq struct {
	Id int64 `path:"id"`
}

type TriggerReq struct {
	WorkflowId int64  `path:"workflowId"`
	Payload    string `json:"payload,optional"`
}

type TriggerResp struct {
	Message     string `json:"message"`
	ExecutionId int64  `json:"executionId"`
}

type UpdateWorkflowReq struct {
	Id            int64  `path:"id"`
	Name          string `json:"name,optional"`
	TriggerType   string `json:"triggerType,optional"`
	TriggerConfig string `json:"triggerConfig,optional"`
	Steps         string `json:"steps,optional"`
	IsActive      bool   `json:"isActive,optional"`
}

type UpdateWorkflowResp struct {
	Ok bool `json:"ok"`
}

type WorkflowItem struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	TriggerType   string `json:"triggerType"`
	TriggerConfig string `json:"triggerConfig"`
	Steps         string `json:"steps"`
	IsActive      bool   `json:"isActive"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token,omitempty"`
	ExpiresIn    int    `json:"expires_in"`
	TokenType    string `json:"token_type"`
}
