// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type ListWorkflowsResp struct {
	Items []WorkflowItem `json:"items"`
	Total int64          `json:"total"`
}

type TriggerReq struct {
	WorkflowId int64 `path:"workflowId"`
}

type TriggerResp struct {
	Message     string `json:"message"`
	ExecutionId int64  `json:"executionId"`
}

type WorkflowItem struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	TriggerType string `json:"triggerType"`
	IsActive    bool   `json:"isActive"`
}
