// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunExecutionReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    int64                  `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkflowId     int64                  `protobuf:"varint,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TriggerPayload string                 `protobuf:"bytes,3,opt,name=trigger_payload,json=triggerPayload,proto3" json:"trigger_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunExecutionReq) Reset() {
	*x = RunExecutionReq{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunExecutionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunExecutionReq) ProtoMessage() {}

func (x *RunExecutionReq) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunExecutionReq.ProtoReflect.Descriptor instead.
func (*RunExecutionReq) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *RunExecutionReq) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *RunExecutionReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *RunExecutionReq) GetTriggerPayload() string {
	if x != nil {
		return x.TriggerPayload
	}
	return ""
}

type RunExecutionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "success" or "failed"
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunExecutionResp) Reset() {
	*x = RunExecutionResp{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunExecutionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunExecutionResp) ProtoMessage() {}

func (x *RunExecutionResp) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunExecutionResp.ProtoReflect.Descriptor instead.
func (*RunExecutionResp) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *RunExecutionResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunExecutionResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "step_done" | "finished"
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "success" | "failed"
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ExecutionEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecutionEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecutionEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x06engine\"~\n" +
	"\x0fRunExecutionReq\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x03R\vexecutionId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\x03R\n" +
	"workflowId\x12'\n" +
	"\x0ftrigger_payload\x18\x03 \x01(\tR\x0etriggerPayload\"@\n" +
	"\x10RunExecutionResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x97\x01\n" +
	"\x0eExecutionEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\x9a\x01\n" +
	"\x0fExecutionEngine\x12A\n" +
	"\fRunExecution\x12\x17.engine.RunExecutionReq\x1a\x18.engine.RunExecutionResp\x12D\n" +
	"\x0fStreamExecution\x12\x17.engine.RunExecutionReq\x1a\x16.engine.ExecutionEvent0\x01B\x15Z\x13execution-engine/pbb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_engine_proto_goTypes = []any{
	(*RunExecutionReq)(nil),  // 0: engine.RunExecutionReq
	(*RunExecutionResp)(nil), // 1: engine.RunExecutionResp
	(*ExecutionEvent)(nil),   // 2: engine.ExecutionEvent
}
var file_engine_proto_depIdxs = []int32{
	0, // 0: engine.ExecutionEngine.RunExecution:input_type -> engine.RunExecutionReq
	0, // 1: engine.ExecutionEngine.StreamExecution:input_type -> engine.RunExecutionReq
	1, // 2: engine.ExecutionEngine.RunExecution:output_type -> engine.RunExecutionResp
	2, // 3: engine.ExecutionEngine.StreamExecution:output_type -> engine.ExecutionEvent
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
