// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionEngine_RunExecution_FullMethodName    = "/engine.ExecutionEngine/RunExecution"
	ExecutionEngine_StreamExecution_FullMethodName = "/engine.ExecutionEngine/StreamExecution"
)

// ExecutionEngineClient is the client API for ExecutionEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionEngineClient interface {
	// RunExecution runs a workflow synchronously and returns when finished.
	RunExecution(ctx context.Context, in *RunExecutionReq, opts ...grpc.CallOption) (*RunExecutionResp, error)
	// StreamExecution runs a workflow and streams progress events back to caller.
	StreamExecution(ctx context.Context, in *RunExecutionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error)
}

type executionEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionEngineClient(cc grpc.ClientConnInterface) ExecutionEngineClient {
	return &executionEngineClient{cc}
}

func (c *executionEngineClient) RunExecution(ctx context.Context, in *RunExecutionReq, opts ...grpc.CallOption) (*RunExecutionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunExecutionResp)
	err := c.cc.Invoke(ctx, ExecutionEngine_RunExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionEngineClient) StreamExecution(ctx context.Context, in *RunExecutionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionEngine_ServiceDesc.Streams[0], ExecutionEngine_StreamExecution_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunExecutionReq, ExecutionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionEngine_StreamExecutionClient = grpc.ServerStreamingClient[ExecutionEvent]

// ExecutionEngineServer is the server API for ExecutionEngine service.
// All implementations must embed UnimplementedExecutionEngineServer
// for forward compatibility.
type ExecutionEngineServer interface {
	// RunExecution runs a workflow synchronously and returns when finished.
	RunExecution(context.Context, *RunExecutionReq) (*RunExecutionResp, error)
	// StreamExecution runs a workflow and streams progress events back to caller.
	StreamExecution(*RunExecutionReq, grpc.ServerStreamingServer[ExecutionEvent]) error
	mustEmbedUnimplementedExecutionEngineServer()
}

// UnimplementedExecutionEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionEngineServer struct{}

func (UnimplementedExecutionEngineServer) RunExecution(context.Context, *RunExecutionReq) (*RunExecutionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RunExecution not implemented")
}
func (UnimplementedExecutionEngineServer) StreamExecution(*RunExecutionReq, grpc.ServerStreamingServer[ExecutionEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamExecution not implemented")
}
func (UnimplementedExecutionEngineServer) mustEmbedUnimplementedExecutionEngineServer() {}
func (UnimplementedExecutionEngineServer) testEmbeddedByValue()                         {}

// UnsafeExecutionEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionEngineServer will
// result in compilation errors.
type UnsafeExecutionEngineServer interface {
	mustEmbedUnimplementedExecutionEngineServer()
}

func RegisterExecutionEngineServer(s grpc.ServiceRegistrar, srv ExecutionEngineServer) {
	// If the following call panics, it indicates UnimplementedExecutionEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionEngine_ServiceDesc, srv)
}

func _ExecutionEngine_RunExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunExecutionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionEngineServer).RunExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionEngine_RunExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionEngineServer).RunExecution(ctx, req.(*RunExecutionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionEngine_StreamExecution_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunExecutionReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutionEngineServer).StreamExecution(m, &grpc.GenericServerStream[RunExecutionReq, ExecutionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionEngine_StreamExecutionServer = grpc.ServerStreamingServer[ExecutionEvent]

// ExecutionEngine_ServiceDesc is the grpc.ServiceDesc for ExecutionEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.ExecutionEngine",
	HandlerType: (*ExecutionEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunExecution",
			Handler:    _ExecutionEngine_RunExecution_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExecution",
			Handler:       _ExecutionEngine_StreamExecution_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "engine.proto",
}
